/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Products API
 * API de referência para o CRUD de Produtos
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";

export type ProductStatus =
  (typeof ProductStatus)[keyof typeof ProductStatus];

export const ProductStatus = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
} as const;

export type Product = {
  /** @format uuid */
  id: string;
  name: string;
  description: string;
  /** @minimum 0 */
  priceInCents: number;
  status: ProductStatus;
  /** @format date-time */
  createdAt: string;
  /** @format date-time */
  updatedAt: string;
};

export type ListProducts200Pagination = {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
};

export type ListProducts200 = {
  data: Product[];
  pagination: ListProducts200Pagination;
};

export type ListProducts401 = {
  error: string;
  code: string;
};

export type ListProducts500 = {
  error: string;
  code: string;
};

export type ListProductsParams = {
  status?: ProductStatus;
  page?: number;
  limit?: number;
};

export type CreateProductBody = {
  name: string;
  description: string;
  /** @minimum 0 */
  priceInCents: number;
  status?: ProductStatus;
};

export type CreateProduct400 = {
  error: string;
  code: string;
};

export type CreateProduct401 = {
  error: string;
  code: string;
};

export type CreateProduct500 = {
  error: string;
  code: string;
};

export type GetProduct401 = {
  error: string;
  code: string;
};

export type GetProduct404 = {
  error: string;
  code: string;
};

export type GetProduct500 = {
  error: string;
  code: string;
};

export type UpdateProductBody = {
  name?: string;
  description?: string;
  /** @minimum 0 */
  priceInCents?: number;
  status?: ProductStatus;
};

export type UpdateProduct400 = {
  error: string;
  code: string;
};

export type UpdateProduct401 = {
  error: string;
  code: string;
};

export type UpdateProduct404 = {
  error: string;
  code: string;
};

export type UpdateProduct500 = {
  error: string;
  code: string;
};

export type DeleteProduct401 = {
  error: string;
  code: string;
};

export type DeleteProduct404 = {
  error: string;
  code: string;
};

export type DeleteProduct500 = {
  error: string;
  code: string;
};

/**
 * @summary List products
 */
export type listProductsResponse200 = {
  data: ListProducts200;
  status: 200;
};

export type listProductsResponse401 = {
  data: ListProducts401;
  status: 401;
};

export type listProductsResponse500 = {
  data: ListProducts500;
  status: 500;
};

export type listProductsResponseSuccess = listProductsResponse200 & {
  headers: Headers;
};
export type listProductsResponseError = (
  | listProductsResponse401
  | listProductsResponse500
) & {
  headers: Headers;
};

export type listProductsResponse =
  | listProductsResponseSuccess
  | listProductsResponseError;

export const getListProductsUrl = (params?: ListProductsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/products?${stringifiedParams}`
    : `/products`;
};

export const listProducts = async (
  params?: ListProductsParams,
  options?: RequestInit,
): Promise<listProductsResponse> => {
  return customFetch<listProductsResponse>(getListProductsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create a product
 */
export type createProductResponse201 = {
  data: Product;
  status: 201;
};

export type createProductResponse400 = {
  data: CreateProduct400;
  status: 400;
};

export type createProductResponse401 = {
  data: CreateProduct401;
  status: 401;
};

export type createProductResponse500 = {
  data: CreateProduct500;
  status: 500;
};

export type createProductResponseSuccess = createProductResponse201 & {
  headers: Headers;
};
export type createProductResponseError = (
  | createProductResponse400
  | createProductResponse401
  | createProductResponse500
) & {
  headers: Headers;
};

export type createProductResponse =
  | createProductResponseSuccess
  | createProductResponseError;

export const getCreateProductUrl = () => {
  return `/products`;
};

export const createProduct = async (
  createProductBody: CreateProductBody,
  options?: RequestInit,
): Promise<createProductResponse> => {
  return customFetch<createProductResponse>(getCreateProductUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createProductBody),
  });
};

/**
 * @summary Get a product
 */
export type getProductResponse200 = {
  data: Product;
  status: 200;
};

export type getProductResponse401 = {
  data: GetProduct401;
  status: 401;
};

export type getProductResponse404 = {
  data: GetProduct404;
  status: 404;
};

export type getProductResponse500 = {
  data: GetProduct500;
  status: 500;
};

export type getProductResponseSuccess = getProductResponse200 & {
  headers: Headers;
};
export type getProductResponseError = (
  | getProductResponse401
  | getProductResponse404
  | getProductResponse500
) & {
  headers: Headers;
};

export type getProductResponse =
  | getProductResponseSuccess
  | getProductResponseError;

export const getGetProductUrl = (productId: string) => {
  return `/products/${productId}`;
};

export const getProduct = async (
  productId: string,
  options?: RequestInit,
): Promise<getProductResponse> => {
  return customFetch<getProductResponse>(getGetProductUrl(productId), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Update a product
 */
export type updateProductResponse200 = {
  data: Product;
  status: 200;
};

export type updateProductResponse400 = {
  data: UpdateProduct400;
  status: 400;
};

export type updateProductResponse401 = {
  data: UpdateProduct401;
  status: 401;
};

export type updateProductResponse404 = {
  data: UpdateProduct404;
  status: 404;
};

export type updateProductResponse500 = {
  data: UpdateProduct500;
  status: 500;
};

export type updateProductResponseSuccess = updateProductResponse200 & {
  headers: Headers;
};
export type updateProductResponseError = (
  | updateProductResponse400
  | updateProductResponse401
  | updateProductResponse404
  | updateProductResponse500
) & {
  headers: Headers;
};

export type updateProductResponse =
  | updateProductResponseSuccess
  | updateProductResponseError;

export const getUpdateProductUrl = (productId: string) => {
  return `/products/${productId}`;
};

export const updateProduct = async (
  productId: string,
  updateProductBody: UpdateProductBody,
  options?: RequestInit,
): Promise<updateProductResponse> => {
  return customFetch<updateProductResponse>(getUpdateProductUrl(productId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateProductBody),
  });
};

/**
 * @summary Delete a product
 */
export type deleteProductResponse204 = {
  data: null;
  status: 204;
};

export type deleteProductResponse401 = {
  data: DeleteProduct401;
  status: 401;
};

export type deleteProductResponse404 = {
  data: DeleteProduct404;
  status: 404;
};

export type deleteProductResponse500 = {
  data: DeleteProduct500;
  status: 500;
};

export type deleteProductResponseSuccess = deleteProductResponse204 & {
  headers: Headers;
};
export type deleteProductResponseError = (
  | deleteProductResponse401
  | deleteProductResponse404
  | deleteProductResponse500
) & {
  headers: Headers;
};

export type deleteProductResponse =
  | deleteProductResponseSuccess
  | deleteProductResponseError;

export const getDeleteProductUrl = (productId: string) => {
  return `/products/${productId}`;
};

export const deleteProduct = async (
  productId: string,
  options?: RequestInit,
): Promise<deleteProductResponse> => {
  return customFetch<deleteProductResponse>(getDeleteProductUrl(productId), {
    ...options,
    method: "DELETE",
  });
};
