/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Products API
 * API de referência para o CRUD de Produtos
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  type QueryFunction,
  type QueryKey,
  type UseMutationOptions,
  type UseMutationResult,
  type UseQueryOptions,
  type UseQueryResult,
} from "@tanstack/react-query";

import { customClientFetch } from "../../fetch-client";
import type {
  CreateProductBody,
  createProductResponse,
  deleteProductResponse,
  getProductResponse,
  ListProductsParams,
  listProductsResponse,
  UpdateProductBody,
  updateProductResponse,
} from "../fetch-generated";

export const getListProductsUrl = (params?: ListProductsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/products?${stringifiedParams}`
    : `/products`;
};

const listProducts = (
  params?: ListProductsParams,
  options?: RequestInit
): Promise<listProductsResponse> => {
  return customClientFetch<listProductsResponse>(getListProductsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListProductsQueryKey = (params?: ListProductsParams) => {
  return ["products", ...(params ? [params] : [])] as const;
};

export const useListProducts = <TError = unknown>(
  params?: ListProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<listProductsResponse, TError, listProductsResponse>
    >;
  }
): UseQueryResult<listProductsResponse, TError> => {
  const queryKey =
    options?.query?.queryKey ?? getListProductsQueryKey(params);

  const queryFn: QueryFunction<listProductsResponse> = () =>
    listProducts(params);

  return useQuery({ queryKey, queryFn, ...options?.query });
};

const getProduct = (
  productId: string,
  options?: RequestInit
): Promise<getProductResponse> => {
  return customClientFetch<getProductResponse>(`/products/${productId}`, {
    ...options,
    method: "GET",
  });
};

export const getGetProductQueryKey = (productId: string) => {
  return ["products", productId] as const;
};

export const useGetProduct = <TError = unknown>(
  productId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<getProductResponse, TError, getProductResponse>
    >;
  }
): UseQueryResult<getProductResponse, TError> => {
  const queryKey = options?.query?.queryKey ?? getGetProductQueryKey(productId);

  const queryFn: QueryFunction<getProductResponse> = () =>
    getProduct(productId);

  return useQuery({
    queryKey,
    queryFn,
    enabled: !!productId,
    ...options?.query,
  });
};

const createProduct = (
  createProductBody: CreateProductBody,
  options?: RequestInit
): Promise<createProductResponse> => {
  return customClientFetch<createProductResponse>(`/products`, {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createProductBody),
  });
};

export const useCreateProduct = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    createProductResponse,
    TError,
    { data: CreateProductBody },
    TContext
  >;
}): UseMutationResult<
  createProductResponse,
  TError,
  { data: CreateProductBody },
  TContext
> => {
  return useMutation({
    mutationFn: ({ data }) => createProduct(data),
    ...options?.mutation,
  });
};

const updateProduct = (
  productId: string,
  updateProductBody: UpdateProductBody,
  options?: RequestInit
): Promise<updateProductResponse> => {
  return customClientFetch<updateProductResponse>(`/products/${productId}`, {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateProductBody),
  });
};

export const useUpdateProduct = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    updateProductResponse,
    TError,
    { productId: string; data: UpdateProductBody },
    TContext
  >;
}): UseMutationResult<
  updateProductResponse,
  TError,
  { productId: string; data: UpdateProductBody },
  TContext
> => {
  return useMutation({
    mutationFn: ({ productId, data }) => updateProduct(productId, data),
    ...options?.mutation,
  });
};

const deleteProduct = (
  productId: string,
  options?: RequestInit
): Promise<deleteProductResponse> => {
  return customClientFetch<deleteProductResponse>(`/products/${productId}`, {
    ...options,
    method: "DELETE",
  });
};

export const useDeleteProduct = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    deleteProductResponse,
    TError,
    { productId: string },
    TContext
  >;
}): UseMutationResult<
  deleteProductResponse,
  TError,
  { productId: string },
  TContext
> => {
  return useMutation({
    mutationFn: ({ productId }) => deleteProduct(productId),
    ...options?.mutation,
  });
};

export type { QueryKey };
